using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StarCommander.Ships
{
    public class ShipNames
    {
        public static Dictionary<int, string> names
        {
            get
            {
                var n = new List<String>();
                n.Add("Callabee");
                n.Add("Jenny Chandris");
                n.Add("Pegasus");
                n.Add("Medusa");
                n.Add("Avola");
                n.Add("Polar 2");
                n.Add("Kadie B");
                n.Add("Petrophalt");
                n.Add("Bever");
                n.Add("Paudion");
                n.Add("Le Vienx Tigre");
                n.Add("Sir Henry Pottinger");
                n.Add("Yaedake Maru");
                n.Add("Kian");
                n.Add("Chateau Yquem");
                n.Add("Kanlaon II");
                n.Add("Elstead");
                n.Add("Carimar");
                n.Add("Consul Cords");
                n.Add("Comandante Paolini");
                n.Add("Pontypool");
                n.Add("Club Sail TWO");
                n.Add("Kate Fitzgerald");
                n.Add("Bad Apple");
                n.Add("Kings Point Victory");
                n.Add("Pembroke Trader");
                n.Add("CNSC 265");
                n.Add("Macungia");
                n.Add("Isabella Fowlie");
                n.Add("Taob");
                n.Add("Marlene");
                n.Add("Novorussia");
                n.Add("Horizonte");
                n.Add("Mayati Maru");
                n.Add("Argun");
                n.Add("Voles");
                n.Add("DONNA");
                n.Add("Joshus A Hatfield");
                n.Add("Wako Maru");
                n.Add("Canadian Engineer");
                n.Add("Rent To Own");
                n.Add("Arthur L Perry");
                n.Add("Le Roi");
                n.Add("Ioan Koutoufaris");
                n.Add("Manu Kai");
                n.Add("Salty Mare");
                n.Add("Northwold");
                n.Add("Rutherford");
                n.Add("Brunante");
                n.Add("Cardiac - A Rest");
                n.Add("Didonta");
                n.Add("Istar");
                n.Add("Brockeswalde");
                n.Add("Cheorio Lads");
                n.Add("Anna Belle II");
                n.Add("Las Vegas Victory");
                n.Add("Cretshawser");
                n.Add("Empire Gilbert");
                n.Add("Busen 6");
                n.Add("Marco Foscarini");
                n.Add("El Paso");
                n.Add("primitive");
                n.Add("Maracay");
                n.Add("Driver");
                n.Add("Angel C");
                n.Add("Luigi Acoame");
                n.Add("Hadati Maru");
                n.Add("Merignao");
                n.Add("Motorex");
                n.Add("Orca");
                n.Add("Christian IX");
                n.Add("Mood Swing");
                n.Add("Vale Royal");
                n.Add("Aslaug");
                n.Add("THE GREAT 68");
                n.Add("Trematon");
                n.Add("Duchess of Hamilton");
                n.Add("Empire Southwold");
                n.Add("Umba");
                n.Add("E 25");
                n.Add("Kiwites");
                n.Add("Shappys Will");
                n.Add("Strathdene");
                n.Add("Slim Jim");
                n.Add("Morning Joy");
                n.Add("Fort Battle River");
                n.Add("Duke William");
                n.Add("Michaels Dream");
                n.Add("Bellechasse");
                n.Add("Cruising Queen");
                n.Add("Zonnewyk");
                n.Add("Lillian Gray");
                n.Add("Pando Cape");
                n.Add("Grecocruz");
                n.Add("Iinston");
                n.Add("Jomac");
                n.Add("Port of London Authority Hopper No 3");
                n.Add("Orita");
                n.Add("Wheelock Whitney");
                n.Add("Nit-Noy");
                n.Add("Komchn");
                n.Add("William T Sherman");
                n.Add("Bruswall");
                n.Add("Air Forced One");
                n.Add("Marine Eagle");
                n.Add("Algethi");
                n.Add("Thirty-Something");
                n.Add("African");
                n.Add("Imperatrice Eugenie");
                n.Add("Holnis");
                n.Add("Yuen Kiang Maru");
                n.Add("East Wales");
                n.Add("Yakacik");
                n.Add("Philoctstes");
                n.Add("Siam");
                n.Add("Cara Mia");
                n.Add("Twice as Nice");
                n.Add("Lienta");
                n.Add("Plaisance");
                n.Add("Fort Wallace");
                n.Add("Maria Teresa Alonso");
                n.Add("China Navigator");
                n.Add("West Eldara");
                n.Add("France Maru");
                n.Add("Camas Meadows");
                n.Add("Dicks Idear");
                n.Add("Puerto de Alcndia");
                n.Add("Christi Li");
                n.Add("Anglo Norse");
                n.Add("Chefoo Maru");
                n.Add("Adder");
                n.Add("Chanteuse");
                n.Add("Fort Wilhelmus");
                n.Add("Malmesbury");
                n.Add("Ode to Presque Isle II");
                n.Add("Sudden Comfort");
                n.Add("Donaghadee");
                n.Add("Phin-Addict");
                n.Add("Labud");
                n.Add("Crash");
                n.Add("Campoamor");
                n.Add("Poseidons Fury");
                n.Add("Linea DOmbra");
                n.Add("Stena Invicta");
                n.Add("Achilles");
                n.Add("Stagen");
                n.Add("Clinton");
                n.Add("Urca");
                n.Add("Travels With Charley");
                n.Add("Port Madison");
                n.Add("Cape Nome");
                n.Add("Agil");
                n.Add("Kaiei Maru");
                n.Add("Cap Fagnet");
                n.Add("El Biar");
                n.Add("Jean-Marie");
                n.Add("Aakre");
                n.Add("tsena");
                n.Add("Fernoliff");
                n.Add("Grelisle");
                n.Add("Star Geiranger");
                n.Add("Ericus");
                n.Add("Nordnorge");
                n.Add("Brissac");
                n.Add("wild rover");
                n.Add("Jib N Tonic");
                n.Add("Comrades");
                n.Add("Olaf Trygveson");
                n.Add("Silver Gate");
                n.Add("Jenny Jewel");
                n.Add("Herrenywk");
                n.Add("Cameron");
                n.Add("Martha Haim");
                n.Add("Monkwood");
                n.Add("Renoir");
                n.Add("Arizona");
                n.Add("not yet - still looking");
                n.Add("Bola");
                n.Add("Vennachar");
                n.Add("Off The Wind");
                n.Add("WONDERFUL");
                n.Add("X TA SEA");
                n.Add("Globe VI");
                n.Add("Alborto");
                n.Add("Albul");
                n.Add("Calbucano");
                n.Add("Halladals");
                n.Add("Behera");
                n.Add("Tjimanoek");
                n.Add("E G B Riley");
                n.Add("Esso Philadelphia");
                n.Add("Alwill");
                n.Add("Atenas");
                n.Add("Fortunale");
                n.Add("Harmattau");
                n.Add("ss titan");
                n.Add("Ginetto");
                n.Add("Lanwerses");
                n.Add("Birkenhead");
                n.Add("Castillo Daroca");
                n.Add("Prissy Miss II");
                n.Add("Nederland");
                n.Add("Avonwood");
                n.Add("Horsbrugh");
                n.Add("Quilliam");
                n.Add("Balthasar");
                n.Add("Liod");
                n.Add("ARGO");
                n.Add("Limena");
                n.Add("Laurita");
                n.Add("Kaereste");
                n.Add("Lora");
                n.Add("Fish Gutz");
                n.Add("Kilwa");
                n.Add("Tempus Fudget");
                n.Add("Booker Venture");
                n.Add("Olderfieet");
                n.Add("Wocana");
                n.Add("Bothnia-38");
                n.Add("Empire Phyllis");
                n.Add("Likomba");
                n.Add("Finale");
                n.Add("Cerridwen");
                n.Add("Komsomol");
                n.Add("Hoa Elo");
                n.Add("Lady Drake");
                n.Add("Newhall Hills");
                n.Add("Lloyd Alegrete");
                n.Add("Auiea");
                n.Add("solveig");
                n.Add("Loveden");
                n.Add("Vincent-Cameleyre");
                n.Add("Tazs Toy");
                n.Add("Mount Vernon");
                n.Add("Bert Reinaner");
                n.Add("Indradeo");
                n.Add("Somme");
                n.Add("Muroto Marn");
                n.Add("N E R No 2");
                n.Add("Manazuru Maru");
                n.Add("Cormead");
                n.Add("Princess of Acadia");
                n.Add("last dance");
                n.Add("Duncannon");
                n.Add("Rio Bravo");
                n.Add("Kamenets-Podolsk");
                n.Add("Abuislah");
                n.Add("Cloverdale");
                n.Add("Havsten");
                n.Add("Lake Sapor");
                n.Add("EL PAISA");
                n.Add("Yun Yang Maru");
                n.Add("Jacana");
                n.Add("Ellenville");
                n.Add("Ban Ho Liong");
                n.Add("RHONDAVOUS");
                n.Add("Bryan Station");
                n.Add("Argo Navis II");
                n.Add("Andrea Sgarallino");
                n.Add("PARTY TIME");
                n.Add("Carousel");
                n.Add("Straat Magelhaen");
                n.Add("G");
                n.Add("Italo");
                n.Add("Wampum");
                n.Add("Empire Madge");
                n.Add("Lynntown");
                n.Add("Pomone");
                n.Add("F Bischoff");
                n.Add("Theresa Jean");
                n.Add("Kau Tung");
                n.Add("Hartbridge");
                n.Add("Rio Tocantins");
                n.Add("Zaanstroom I");
                n.Add("Reka");
                n.Add("Miss Tress");
                n.Add("Colonel Mustard");
                n.Add("wheezer");
                n.Add("Uskmoor");
                n.Add("Wiking 1");
                n.Add("Durga");
                n.Add("Chalice");
                n.Add("Daressa");
                n.Add("Donald B Gillies");
                n.Add("Kaitawa");
                n.Add("Black Osprey");
                n.Add("Lednor");
                n.Add("Hardhack");
                n.Add("Passing Wind");
                n.Add("Shenandoah");
                n.Add("Truncheon");
                n.Add("Cremer");
                n.Add("Yo Pisces");
                n.Add("Donald S Wright");
                n.Add("F M Whittaker");
                n.Add("Tender Genova");
                n.Add("British Captain");
                n.Add("Nailsea River");
                n.Add("Lagundu");
                n.Add("Norah Moller");
                n.Add("Ritzy");
                n.Add("Olivus II");
                n.Add("Sting");
                n.Add("Choun Maru No 10");
                n.Add("Francunion V");
                n.Add("Eunice P Newcomb");
                n.Add("Grand Mesa");
                n.Add("Meriwether Lewis");
                n.Add("Afridi");
                n.Add("Ingenieur General Haarbleicher");
                n.Add("Kinyo Maru No 2");
                n.Add("Myfjord");
                n.Add("Chin Lung");
                n.Add("Koodori");
                n.Add("Marie Galante");
                n.Add("Daikokusan Maru");
                n.Add("Persia L");
                n.Add("Pirates/40");
                n.Add("PINTA");
                n.Add("Nestorian");
                n.Add("Haugland");
                n.Add("Chye Sah Lee");
                n.Add("Time For Us");
                n.Add("St Andrews");
                n.Add("Glendaruel");
                n.Add("Norlys");
                n.Add("Mulcra");
                n.Add("Colleville");
                n.Add("White Fan");
                n.Add("Novorossisk");
                n.Add("Full Circle");
                n.Add("Charles Heiden");
                n.Add("Katriena");
                n.Add("Begerin");
                n.Add("Island Chief");
                n.Add("Camille");
                n.Add("Baron Loudoun");
                n.Add("Flandre");
                n.Add("C W Lawrence");
                n.Add("Loch Harport");
                n.Add("Kvaholmen");
                n.Add("General Bonaparte");
                n.Add("Hlaing");
                n.Add("Reel Work");
                n.Add("Enes");
                n.Add("Wakool");
                n.Add("Ville de Hambourg");
                n.Add("West Modes");
                n.Add("NEPTUNE");
                n.Add("Bjarnarey");
                n.Add("Enseigne-Fleuri");
                n.Add("Mahratta");
                n.Add("Oceaan 4");
                n.Add("Panama Express");
                n.Add("Embirlcos");
                n.Add("Kanzaki Maru");
                n.Add("Esso Manhattan");
                n.Add("Chilton Seam");
                n.Add("Daisho Maru No 2");
                n.Add("Menominee");
                n.Add("Liban");
                n.Add("Sir George");
                n.Add("Island Rhythm");
                n.Add("Coastal Drifter");
                n.Add("Frieden");
                n.Add("Grodno");
                n.Add("Angel");
                n.Add("Perlen");
                n.Add("Yoshu Maru");
                n.Add("Koki Maru No 5");
                n.Add("Fort Boise");
                n.Add("N E R No 7");
                n.Add("Craigsmere");
                n.Add("mojo");
                n.Add("Luftschatz");
                n.Add("Hareid");
                n.Add("Port Bowen");
                n.Add("Gumbinnen");
                n.Add("Andria");
                n.Add("Duke of Connaught");
                n.Add("FISH BIZ");
                n.Add("Marthas Way");
                n.Add("Pentower");
                n.Add("Cape Edmont");
                n.Add("Final Choice");
                n.Add("Matthew");
                n.Add("Lowea");
                n.Add("Wace Victory");
                n.Add("Oldambt");
                n.Add("Gondul");
                n.Add("Eriksholm");
                n.Add("Brackenfleld");
                n.Add("Benjamin Tay");
                n.Add("Wandia");
                n.Add("Another One Of These Days");
                n.Add("Mavis");
                n.Add("Loch Swin");
                n.Add("Zatrick");
                n.Add("Cornore");
                n.Add("Brinckmann");
                n.Add("Heim");
                n.Add("Albert Hulett");
                n.Add("Granite");
                n.Add("Bushwood");
                n.Add("Lys");
                n.Add("Aubretia");
                n.Add("A*WO*L*");
                n.Add("AVRA");
                n.Add("Giyn Marn No 2");
                n.Add("Laiva");
                n.Add("Linfield Victory");
                n.Add("Veg");
                n.Add("Pepita Colomer");
                n.Add("Coralstone");
                n.Add("Chattanooga City");
                n.Add("Guarico");
                n.Add("Hedwige");
                n.Add("Huasco");
                n.Add("Berlin");
                n.Add("Benjamin D Wilson");
                n.Add("Malte");
                n.Add("Farrapo");
                n.Add("Kanzler");
                n.Add("Cassar");
                n.Add("Posang");
                n.Add("Aloan at Last");
                n.Add("DAYSTAR DANCER");
                n.Add("Gamhada");
                n.Add("Frutera");
                n.Add("Windhorse");
                n.Add("Chances Are");
                n.Add("Grace A Barrett");
                n.Add("Dauntless No 12");
                n.Add("Yandra");
                n.Add("Brunelle");
                n.Add("Buccari");
                n.Add("Baltavia");
                n.Add("Ingeborg S");
                n.Add("Wilhelmsberg");
                n.Add("Gymerie");
                n.Add("Mormaclark");
                n.Add("Cape Leenwin");
                n.Add("Princess Norah");
                n.Add("Lil Giant II");
                n.Add("Marjerie");
                n.Add("Ultra Viole");
                n.Add("Loide Honduras");
                n.Add("Apurimac");
                n.Add("Empire Lilliput");
                n.Add("Shari S");
                n.Add("Cest Si Bon");
                n.Add("Cadence");
                n.Add("Beppo Maru");
                n.Add("Empire Concrete");
                n.Add("Ahrensburg");
                n.Add("Fridius");
                n.Add("Shameless Cs");
                n.Add("Rona");
                n.Add("Harpalyous");
                n.Add("Mao Lee");
                n.Add("Daisan Maru");
                n.Add("Yeijun Maru");
                n.Add("H Westfal Larsen");
                n.Add("Hery");
                n.Add("Panga");
                n.Add("Oppelia Delmas");
                n.Add("Scholar");
                n.Add("James W Nesmith");
                n.Add("SS Cherlitta");
                n.Add("Cape Spartel");
                n.Add("Rosaura");
                n.Add("Carl R Gray");
                n.Add("Biarritz");
                n.Add("George Henry");
                n.Add("Mayfiower");
                n.Add("Masskerk");
                n.Add("Tullamore");
                n.Add("Eastwind");
                n.Add("KIM");
                n.Add("Mars II");
                n.Add("Burton");
                n.Add("Castillo Montesa");
                n.Add("Grong");
                n.Add("Quintero");
                n.Add("Wikinger");
                n.Add("Elihu B Washburne");
                n.Add("Istriano");
                n.Add("Westlin Winds");
                n.Add("Conservator");
                n.Add("Damas");
                n.Add("Uchinoumi Maru No 8");
                n.Add("Jamaica Planter");
                n.Add("Empire Garrison");
                n.Add("Comoyagua");
                n.Add("Great Zabra");
                n.Add("Cronshagen");
                n.Add("Opobo");
                n.Add("Iturri-Urdifie");
                n.Add("Cecilia K");
                n.Add("Hiro Maru No 2");
                n.Add("Bramora");
                n.Add("Next Friday");
                n.Add("Kyo Maru No 6");
                n.Add("Linnet");
                n.Add("Koa Maru No 2");
                n.Add("Jos Maria");
                n.Add("Baymand");
                n.Add("Oltenia");
                n.Add("Rough Rider");
                n.Add("Dalliance");
                n.Add("CALDNSICK");
                n.Add("Hinrioh");
                n.Add("High Spirits");
                n.Add("Fort Glenora");
                n.Add("MS MAGOO");
                n.Add("Mariane");
                n.Add("Legend");
                n.Add("Jamaica Pioneer");
                n.Add("Kyra-Panagia");
                n.Add("John Payne");
                n.Add("Mutual Fun");
                n.Add("Valverde");
                n.Add("Glenbridge");
                n.Add("Menura");
                n.Add("Kasugasan Maru");
                n.Add("Háifoss");
                n.Add("Barney Kirsohbaum");
                n.Add("NAMASTE");
                n.Add("lets dance");
                n.Add("Ball Brothere");
                n.Add("RIMRACKED");
                n.Add("Cap St Jaeques");
                n.Add("St Winifred");
                n.Add("Van Hentsz");
                n.Add("Melpomene");
                n.Add("West Linn Victory");
                n.Add("Lao");
                n.Add("Golden Fleece");
                n.Add("Boliviana");
                n.Add("Wellfield");
                n.Add("Mary Johnston");
                n.Add("Periwinkle");
                n.Add("Canadian Construotor");
                n.Add("Croxby");
                n.Add("GRENADE");
                n.Add("Goodtidengs");
                n.Add("Maricholm");
                n.Add("Yenisei");
                n.Add("George F Patten");
                n.Add("Lorraine Rita");
                n.Add("Sunny Side Up");
                n.Add("Izmir");
                n.Add("Bavonside");
                n.Add("Lacedaemonian");
                n.Add("MAH");
                n.Add("ACE");
                n.Add("Highcliffe");
                n.Add("Westcoates");
                n.Add("RAINBOW");
                n.Add("Intrigue");
                n.Add("Frank R Stockton");
                n.Add("Aquaculture");
                n.Add("moby dick");
                n.Add("Levin J Marvel");
                n.Add("sanbbar hunter");
                n.Add("City of Bristol");
                n.Add("athena");
                n.Add("Empire Galashiels");
                n.Add("Kalila");
                n.Add("Bay Rover");
                n.Add("Grangetown");
                n.Add("Platypus III");
                n.Add("Island Home");
                n.Add("Ernst Schweckendieck");
                n.Add("Moses Rogers");
                n.Add("Heliekis");
                n.Add("Expert");
                n.Add("Osterndorf");
                n.Add("Doonass");
                n.Add("Maurice et Reunion");
                n.Add("Aldersdale");
                n.Add("Hemlock");
                n.Add("Tasso");
                n.Add("Archers Hope");
                n.Add("Cobi");
                n.Add("Dream BIG");
                n.Add("Montbeliard");
                n.Add("Admiral Karl Haring");
                n.Add("Morning After");
                n.Add("Delfdijk");
                n.Add("Odine");
                n.Add("Yamato Maru");
                n.Add("Gael");
                n.Add("Vittoria V");
                n.Add("Charles Henderson");
                n.Add("Meiji Maru No 5");
                n.Add("Sungei Asahan");
                n.Add("Marajo");
                n.Add("Lyons Maru");
                n.Add("Vige");
                n.Add("Lae");
                n.Add("Baldo");
                n.Add("Ile dOuessant");
                n.Add("Shibetoro Maru");
                n.Add("Western City");
                n.Add("Pere Marquette 22");
                n.Add("Asbjrn");
                n.Add("New York");
                n.Add("Quotabuster");
                n.Add("Fort Walsh");
                n.Add("Highley Commissioned");
                n.Add("Donna Maria Segunda");
                n.Add("Hot Topic");
                n.Add("Esperos");
                n.Add("Lamy");
                n.Add("Strasbourg");
                n.Add("Costantinopoli");
                n.Add("Lanyard");
                n.Add("Moby Deck");
                n.Add("Pilot Knob");
                n.Add("BAHWNo11");
                n.Add("Dockyard VIII");
                n.Add("Baharakat");
                n.Add("Sunburst");
                n.Add("Garmania");
                n.Add("Shebeen");
                n.Add("Arvika");
                n.Add("James Hawson");
                n.Add("Greth");
                n.Add("Cad Hassan");
                n.Add("Light Wave");
                n.Add("Moonmyst");
                n.Add("Redonda");
                n.Add("Ocean Coek");
                n.Add("reality check");
                n.Add("Quilliam");
                n.Add("Amanda Rhos");
                n.Add("Dagmar Bratt");
                n.Add("City of Midland");
                n.Add("Koralen I");
                n.Add("Eridano");
                n.Add("Eugowra");
                n.Add("Gladrags");
                n.Add("Andr Thom");
                n.Add("Jackstay");
                n.Add("Tresithney");
                n.Add("Shadow Star");
                n.Add("African Grove");
                n.Add("Aighai");
                n.Add("Mormacfir");
                n.Add("Carlos Lumb");
                n.Add("Port Napier");
                n.Add("southern cross");
                n.Add("One For Fun");
                n.Add("Chinook");
                n.Add("Kako Maru");
                n.Add("Quick N Dirty");
                n.Add("Algie");
                n.Add("Shootin the Breeze");
                n.Add("Ida Cuneo");
                n.Add("Kirkholmen");
                n.Add("Nissho Maru No 3");
                n.Add("Verseau");
                n.Add("Nicos Valmadis");
                n.Add("J H Wilhelms");
                n.Add("Glenfinnart");
                n.Add("Emiel Vandervelde");
                n.Add("Holmglen");
                n.Add("Hrvat");
                n.Add("Ordunte-Mendi");
                n.Add("Arin-Mendi");
                n.Add("John Merrick");
                n.Add("Mulgrave Park");
                n.Add("whisper");
                n.Add("Loch Gorm");
                n.Add("Tambov");
                n.Add("Queensland Star");
                n.Add("John F Carroll");
                n.Add("Ivaran");
                n.Add("Alberto Trevee");
                n.Add("Charles Perter Low");
                n.Add("Merapi");
                n.Add("Gabriel Duval");
                n.Add("Helene Woermann");
                n.Add("Lake Winnipeg");
                n.Add("Werdenfels");
                n.Add("Madge Llewellyn");
                n.Add("Lucia C");
                n.Add("Charles Tellier");
                n.Add("Jalamokambi");
                n.Add("Caleb Strong");
                n.Add("Viator");
                n.Add("Narbada");
                n.Add("Earmina");
                n.Add("LOKA");
                n.Add("Beautiful Swimmer");
                n.Add("Nordstjornan");
                n.Add("Varing");
                n.Add("Marie Maersk");
                n.Add("Rapture");
                n.Add("Itria");
                n.Add("Northcliffe");
                n.Add("Plan-b");
                n.Add("Voiubilis");
                n.Add("Merknr");
                n.Add("Jean & Joyce");
                n.Add("Golddrift");
                n.Add("Mapia");
                n.Add("Quisqueya");
                n.Add("True Dreamer");
                n.Add("Fukuei Maru No 2");
                n.Add("Booker Crusade");
                n.Add("Kanmon Maru No 4");
                n.Add("Samuel Plimsoll");
                n.Add("Meandre");
                n.Add("Aralizz");
                n.Add("Nordanbris");
                n.Add("Matsumoto Maru");
                n.Add("Modus Vivendi");
                n.Add("Mood Swing");
                n.Add("Manava");
                n.Add("Kvalen");
                n.Add("Fawlty Beagle");
                n.Add("Daggry");
                n.Add("Francoli");
                n.Add("Cricamola");
                n.Add("Gorsethorn");
                n.Add("Only Interest");
                n.Add("Great Nicholas");
                n.Add("KYRO");
                n.Add("Kite Runner");
                n.Add("santana");
                n.Add("Felipa");
                n.Add("Philol");
                n.Add("REBEL");
                n.Add("Polytrader");
                n.Add("Peaches 5");
                n.Add("Hydro-Therapy");
                n.Add("Meganom");
                n.Add("Agamemnon");
                n.Add("Odyssey Of My Soul");
                n.Add("Newa");
                n.Add("C P Raymond");
                n.Add("Jean Jadot");
                n.Add("Calico Sky");
                n.Add("Matzkau");
                n.Add("Antalya");
                n.Add("Hurricane Hutch");
                n.Add("Clan Lamont");
                n.Add("Denia");
                n.Add("Jose de Larrinaga");
                n.Add("Scout");
                n.Add("Silverkite");
                n.Add("Bharasindhu");
                n.Add("Cambrian Idylle");
                n.Add("Soclose");
                n.Add("Skier");
                n.Add("Kratos");
                n.Add("Daniel Steinmann");
                n.Add("Manilla");
                n.Add("Amersfoort");
                n.Add("Kosarew");
                n.Add("City of San Antonio");
                n.Add("Irish Mist");
                n.Add("Hoangito");
                n.Add("Lake Galewood");
                n.Add("Nanna");
                n.Add("Imbrim");
                n.Add("Fullerton Rose");
                n.Add("Luneberg");
                n.Add("Har Carmel");
                n.Add("Anni");
                n.Add("Out of Town");
                n.Add("Kvishak");
                n.Add("Atwood");
                n.Add("Phlox");
                n.Add("Colleen");
                n.Add("Courlis");
                n.Add("Generalkonsul Pallisen");
                n.Add("Fort-Niagara");
                n.Add("Jalanthony");
                n.Add("Askari");
                n.Add("Missouri");
                n.Add("Summerset");
                n.Add("Directeur Gerling");
                n.Add("Prestonian");
                n.Add("Knut");
                n.Add("Off Course");
                n.Add("Gleniffer");
                n.Add("Joop Sloop");
                n.Add("Dream a little dream");
                n.Add("Uschi Too");
                n.Add("Dovana");
                n.Add("Pipestone County");
                n.Add("Cavour");
                n.Add("Cynosure");
                n.Add("Castifiore");
                n.Add("Horst Wessel");
                n.Add("Henrik Amela");

                Dictionary<int, string> myNames = new Dictionary<int, string>();
                int key = 0;
                foreach (var s in n)
                {
                    key++;
                    myNames.Add(key, s);
                }

                return myNames;
            }
        }
    }
}
